USE Test;

INSERT INTO test.machines (id, factory_id, product, time) VALUES (1, 0, 'ProductA', 1);
INSERT INTO test.machines (id, factory_id, product, time) VALUES (2, 0, 'ProductB', 2);
INSERT INTO test.machines (id, factory_id, product, time) VALUES (3, 0, 'ProductC', 3);
INSERT INTO test.machines (id, factory_id, product, time) VALUES (4, 0, 'ProductB', 1);
INSERT INTO test.machines (id, factory_id, product, time) VALUES (5, 0, 'ProductA', 3);
INSERT INTO test.machines (id, factory_id, product, time) VALUES (6, 0, 'ProductC', 2);